import cv2
import imutils
import sys
image = cv2.imread("nature.png")
grayImage = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
image_gray = cv2.imread("nature.png", cv2.IMREAD_GRAYSCALE)
image_flip = cv2.imread("nature.png")
resizedImg = imutils.resize(image, width=500)
cv2.imshow('Original', image)
cv2.imwrite('graynew.jpeg', grayImage)
cv2.imwrite('resizedImg2.png', resizedImg)
cv2.imshow('Gray', grayImage)
_, th_binary = cv2.threshold(image_gray, 124, 255, cv2.THRESH_BINARY)
_, th_binary_inv = cv2.threshold(image_gray, 124, 255, cv2.THRESH_BINARY_INV)
_, th_trunc = cv2.threshold(image_gray, 124, 255, cv2.THRESH_TRUNC)
_, th_tozero = cv2.threshold(image_gray, 124, 255, cv2.THRESH_TOZERO)
_, th_tozero_inv = cv2.threshold(image_gray, 124, 255, cv2.THRESH_TOZERO_INV)
cv2.imshow("Original", image_gray)
cv2.imshow("Binary", th_binary)
cv2.imshow("Binary Inverse", th_binary_inv)
cv2.imshow("Trunc", th_trunc)
cv2.imshow("To Zero", th_tozero)
cv2.imshow("To Zero Inverse", th_tozero_inv)
horizontal_flip = cv2.flip(image_flip, 1)
vertical_flip = cv2.flip(image_flip, 0)
both_flips = cv2.flip(image_flip, -1)
cv2.imshow('Original Image', image_flip)
cv2.imshow('Horizontal Flip', horizontal_flip)
cv2.imshow('Vertical Flip', vertical_flip)
cv2.imshow('Horizontal & Vertical Flip', both_flips)
cv2.waitKey(10000) 
cv2.destroyAllWindows()
